### ISSUE TITLE
Insync new version

### ISSUE THREAD

**Issue by myszkin81** [ppfeufer/gentoo-overlay#1]
I have noticed that current net-misc/insync stopped working and a new version of Insync is available (3.1.2.40785) for download. Changing the ebuild version and patches filenames resulted in proper ebuild merge. Can you add a new ebuild?

**Comment by ppfeufer** [comment]
Oh sorry, haven't noticed this message here.
ebuilds are updated as soon as I find out there is a new version, just added v3.1.4.40795.
