### ISSUE TITLE
Stray github-desktop ebuild in dev-vcs/gitkraken

### ISSUE THREAD

**Issue by lupusbytes** [ppfeufer/gentoo-overlay#13]
Stray file [dev-vcs/gitkraken/github-desktop-3.2.7-r2.ebuild](https://github.com/ppfeufer/gentoo-overlay/blob/29aeaf74fa46297d1ca70d80d7d36b0d1ea91d0b/dev-vcs/gitkraken/github-desktop-3.2.7-r2.ebuild) is causing problems for portage.
`Invalid ebuild name: /var/db/repos/ppfeufer-gentoo-overlay/dev-vcs/gitkraken/github-desktop-3.2.7-r2.ebuild`

**Comment by ppfeufer** [comment]
Thanks for the report, the ebuild has been moved to the right directory.
