### ISSUE TITLE
dev-vcs/github-desktop-3.3.3-r2 digest verification failed

### ISSUE THREAD

**Issue by adamwiw** [ppfeufer/gentoo-overlay#16]
Computer /var/db/repos # emerge github-desktop -a

These are the packages that would be merged, in order:

Calculating dependencies   * waiting for lock on /var/db/.pkg.portage_lockfile ...                                                                                                                                                    [ ok ]
... done!
Dependency resolution took 5.73 s.

[ebuild  N    ~] dev-vcs/github-desktop-3.3.3-r2  USE="-alacritty" 

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

!!! Digest verification failed:
!!! /var/db/repos/ppfeufer-gentoo-overlay/dev-vcs/github-desktop/metadata.xml
!!! Reason: Filesize does not match recorded size
!!! Got: 220
!!! Expected: 224

**Comment by ppfeufer** [comment]
Oh, I see what happened here, just pushed a fix, give it an hour or two to be propagated to Gentoo's repo upstream.
