### ISSUE TITLE
Libthai size mismatch

### ISSUE THREAD

**Issue by jbhanks** [ppfeufer/gentoo-overlay#17]
Hi, not sure if this is an issue with the repo or on my end, but I got this when trying to emerge libthai (after running `emerge --sync`)

```
!!! Digest verification failed:
!!! /var/db/repos/ppfeufer-gentoo-overlay/dev-libs/libthai/files/libthai-0.1.28-fix-duplicate-dir.patch
!!! Reason: Filesize does not match recorded size
!!! Got: 702
!!! Expected: 704
```
Apologies if this isn't relevant to you.

**Comment by ppfeufer** [comment]
Oh?

Haven' touched that in a while, let me check.

**Comment by ppfeufer** [comment]
Manifest has been re-generated, this should take care of it.

**Comment by jbhanks** [comment]
That did the trick, thanks for the speedy reply.
