### ISSUE TITLE
sys-boot/ventoy-bin-1.0.96::ppfeufer-gentoo-overlay

### ISSUE THREAD

**Issue by geosone** [ppfeufer/gentoo-overlay#18]
i tried to merge your package but it failes on the sanitize.patch 

`[ebuild  N    ~] sys-boot/ventoy-bin-1.0.96::ppfeufer-gentoo-overlay  19.490 KiB

Total: 2 packages (2 new), Size of downloads: 19.758 KiB

>>> Verifying ebuild manifests

!!! Digest verification failed:
!!! /var/db/repos/ppfeufer-gentoo-overlay/sys-boot/ventoy-bin/files/sanitize.patch
!!! Reason: Filesize does not match recorded size
!!! Got: 4367
!!! Expected: 4399
`

i then made a redisgest in the hope it would help

` * Applying sanitize.patch ...
patching file tool/ventoy_lib.sh
Hunk #2 FAILED at 52.
Hunk #3 FAILED at 311.
2 out of 3 hunks FAILED -- saving rejects to file tool/ventoy_lib.sh.rej
patching file tool/VentoyWorker.sh
Hunk #1 succeeded at 106 (offset 1 line).
patching file Ventoy2Disk.sh
Hunk #1 FAILED at 32.
1 out of 1 hunk FAILED -- saving rejects to file Ventoy2Disk.sh.rej
patching file VentoyPlugson.sh
patching file VentoyWeb.sh
Hunk #1 succeeded at 15 with fuzz 1.                                                                                                                                                                       [ !! ]
`

but it is failing.

**Comment by ppfeufer** [comment]
This should be fixed, sorry for the inconvenience.

**Comment by geosone** [comment]
thx

**Comment by geosone** [comment]
by the way here is my repo https://gitea.disconnected-by-peer.at/dbp/linamh
