### ISSUE TITLE
dev-vcs/gitkraken depends on net-print/cups

### ISSUE THREAD

**Issue by techneaponahi** [ppfeufer/gentoo-overlay#2]
Hey, I noticed that gitkraken depends on net-print/cups. It complains that it can't find libcups.so.2 if it isn't installed and refuses to start.

Also the permissions of /usr/share/gitkraken/chrome-sandbox need to have suid bit set or it gives the error:
[22555:0626/222333.345375:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/gitkraken/chrome-sandbox is owned by root and has mode 4755.

adding 
RDEPEND="net-print/cups"

and
fperms 4755 /usr/share/gitkraken/chrome-sandbox

fixed it for me.
Just a heads up.

**Comment by ppfeufer** [comment]
Can you submit a pull request please?

**Comment by ppfeufer** [comment]
"net-print/cups" is added as dependency. As for your fperms issue, this seems to be an issue with electron itself, which I can't re-create on my machine.

```
gitkraken # ll
total 193M
-rw-r--r-- 1 root root  21M Jul 19 13:21 snapshot_blob.bin
-rw-r--r-- 1 root root 2.9M Jul 19 13:21 libffmpeg.so
-rw-r--r-- 1 root root 174K Jul 19 13:21 chrome_100_percent.pak
-rw-r--r-- 1 root root  81K Jul 19 13:21 natives_blob.bin
-rw-r--r-- 1 root root  19K Jul 19 13:21 gitkraken.png
-rw-r--r-- 1 root root 1.1K Jul 19 13:21 LICENSE.electron
-rwxr-xr-x 1 root root 111M Jul 19 13:21 gitkraken
-rw-r--r-- 1 root root  22M Jul 19 13:21 v8_context_snapshot.bin
-rw-r--r-- 1 root root 8.3M Jul 19 13:21 resources.pak
-rw-r--r-- 1 root root    6 Jul 19 13:21 version
-rw-r--r-- 1 root root   22 Jul 19 13:21 LICENSE
-rw-r--r-- 1 root root 8.0M Jul 19 13:21 libGLESv2.so
-rw-r--r-- 1 root root 310K Jul 19 13:21 chrome_200_percent.pak
-rw-r--r-- 1 root root  10M Jul 19 13:21 icudtl.dat
-rw-r--r-- 1 root root 243K Jul 19 13:21 libEGL.so
-rw-r--r-- 1 root root 5.4M Jul 19 13:21 chrome-sandbox
-rw-r--r-- 1 root root 4.5M Jul 19 13:21 LICENSES.chromium.html
drwxr-xr-x 2 root root 4.0K Jul 19 13:21 swiftshader
drwxr-xr-x 2 root root 4.0K Jul 19 13:21 locales
drwxr-xr-x 3 root root 4.0K Jul 19 13:21 resources
```

This works for me.

**Comment by ppfeufer** [comment]
@blacknfuzzy :: Does this solution work for you?

**Comment by techneaponahi** [comment]
Ah, Yes it does. Thanks. Sorry for not responding earlier.
