### ISSUE TITLE
app-admin/enpass: Support apulse

### ISSUE THREAD

**Issue by Anonymous1157** [ppfeufer/gentoo-overlay#3]
Thanks for making this ebuild.

I don't want to have PulseAudio on my system so I configure applications to use apulse instead, but I don't globally enable apulse in ld.so.conf because some applications that still support both PulseAudio and ALSA behave better with one or the other.

This ebuild is written to hard-depend on PulseAudio but Enpass actually works fine with apulse. It would be cool if the ebuild supports both options.

I modified the ebuild like this to try it out:
1. Change the PulseAudio dependency to `|| ( media-sound/pulseaudio media-sound/apulse )`
2. Change `/usr/bin/enpass` to a wrapper script that runs `LD_PRELOAD=/usr/lib64/apulse/libpulse.so.0 /opt/enpass/Enpass`

This should work on systems with either PulseAudio or apulse installed but it will prefer apulse if both are installed. I don't see this as a problem since the application has a hard dependency on libpulse for literally one single sound effect.

An alternate way to implement it is with a "pulseaudio" useflag that chooses which dependency and whether to use this wrapper. It seems like too much effort for how this application uses sound (barely).

**Comment by Anonymous1157** [comment]
Oops, I brainfarted... apulse includes a wrapper script `/usr/bin/apulse` that has a better way of starting the executable than that `LD_PRELOAD` line, better to use that instead.

**Comment by ppfeufer** [comment]
Nice, closed by a commit ...

**Comment by ppfeufer** [comment]
Hey there,

I updated the ebuild. could you test if that fixes your issue?

**Comment by Anonymous1157** [comment]
Yes, thank you! The new ebuild installs and runs fine without changes.

**Comment by ppfeufer** [comment]
Awesome!
Closing this then.
