### ISSUE TITLE
net-misc/insync segfault

### ISSUE THREAD

**Issue by myszkin81** [ppfeufer/gentoo-overlay#4]
Each time I start Insync it crashes immediately with this message in dmesq
```
insync[12899]: segfault at 1e8 ip 00007f2f680b9f64 sp 00007ffe344fef90 error 4 in libpython3.7m.so.1.0[7f2f68054000+17e000]

Code: 57 10 48 89 77 08 48 c7 07 01 00 00 00 c3 0f 1f 84 00 00 00 00 00 e9 7b b4 f9 ff 66 66 2e 0f 1f 84 00 00 00 00 00 53 48 89 fb <48> 8b 7f 20 e8 f3 be f9 ff 48 85 c0 74 0e 48 89 58 08 48 c7 00 01
```

Adding 
`RESTRICT="strip"`
to ebuild file fixes the issue.

The solution is form insync forums
https://forums.insynchq.com/t/segfault-libpython3-7m-so-1-0/16999

**Comment by myszkin81** [comment]
@ppfeufer The issue still persists in latest insync ebuild

**Comment by ppfeufer** [comment]
Can you confirm please if it should be `RESTRICT="strip"` or `RESTRICT=“SPLIT”` as mentioned in the forum post you linked?

**Comment by myszkin81** [comment]
@ppfeufer 
`RESTRICT="strip"` solved my case

**Comment by ppfeufer** [comment]
Well, here we go
