### ISSUE TITLE
Non executable permission with gitkraken

### ISSUE THREAD

**Issue by upshe** [ppfeufer/gentoo-overlay#5]
When gitkraken is installed the executable at /usr/bin/gitkraken doesn't have the execution permission, it can be solved with chmod +x /usr/bin/gitkraken (as a root user or with sudo/doas), but maybe it will be good to add that into the ebuild.

**Comment by ppfeufer** [comment]
Nice catch. Although `/usr/bin/gitkraken` had the +x flag, but not its link target.
