### ISSUE TITLE
net-misc/insync-3.7.9.50368: wrong https site

### ISSUE THREAD

**Issue by HougeLangley** [ppfeufer/gentoo-overlay#6]
`>>> Downloading 'http://s.insynchq.com/builds/insync_3.7.9.50368-bullseye_amd64.deb'`

![2022-08-14_20-57](https://user-images.githubusercontent.com/1161594/184537978-ecdebf24-dd02-478b-ab54-36b99f69b340.png)

`https://cdn.insynchq.com/builds/linux/insync_3.7.9.50368-bullseye_amd64.deb`

maybe the right one.

**Comment by ppfeufer** [comment]
Hey there,

Thanks for reporting this and sorry for the late reply (Somehow GitHub didn't send me a mail for this one).

This is fixed with the 3.7.11 release, the older versions will be removed with todays cleanup.
